config/routes.rb
Rails.application.routes.draw do

  get 'test_react/index'
  get 'hello_world', to: 'hello_world#index'
  get 'contacts/index'

  get 'contacts/show'

  get 'contacts/new'

  get 'contacts/edit'

  namespace :api, defoult: {:format => :json}do
  namespace :v1 do
  	resources :posts
  end
end
	get 'users/index'
	get 'sessions/login'
	get 'sessions/logout'

	post 'sessions/attempt_login'
	# get 'pages/show'

  resources :pages
  resources :contacts
  resources :posts do
    resources :comments
  end

root "posts#index"
#match ':controller(/:action(/:id))' , :via => [:get,:post]
get "/about", to: "pages#about"

end

app/views/layouts/_application.html.erb
<!-- here is the home page disagn that applay on all pages in app -->
<!DOCTYPE html>
<html>
  <head>
    <title>MaJeD BoJaN's article</title>

  	<%= csrf_meta_tags %>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=raleway:400,700'%>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

<body>
  <div id="sidebar">
    <div id="logo">
     <!-- <= image_tag @profile.image.url(:thumb)%> -->
      <img src="majed.jpg" class="img-circle img-responsive" alt="Cinque Terre" width="304" height="236">
    </div>

    <ul>
      <li class="category"> Website</li>
      <li><%= link_to "Blogs", root_path %></li>
      <li><%= link_to "About", page_path(params[:id] = 1) %></li>
    </ul>

    <ul>
      <li class="category">Social</li>
      <li><a href="https://facebook.com/majedbojan">Facebook</a></li>
      <li><a href="https://twitter.com/majedbojan">Twitter</a></li>
      <li><a href="https://github.com/majedbojan">Github</a></li>
    </ul>

    <ul>
      <li>
        <p class="sign_in">Admin Login</p>
      </li>
    </ul>
  </div>

  <div id="main_content">

  <div id="header">

    <!-- <div id="logo">
  </div> -->
    <img src="majed.jpg" class="img-circle img-responsive" alt="Cinque Terre" width="50px" right="6em" top="3em" >
    <% if current_page?(root_path)%>
      <p>All posts</p>
    <% elsif current_page?(about_path)%>
      <p>About</p>
    <% elsif current_page?(@user)%>
    <P><%= link_to "Back to accounts", sessions_login_path %></P>
    <%else%>
    <%= link_to "Back to all blogs", root_path%>
    <%end%>
    <div class="buttons">
    <% if !session[:email].blank?%>
    <%=link_to "new post", new_post_path,  class: 'button' %>
    <%end%>
    <%= link_to 'Admin',{:controller =>'sessions' ,:action => 'login'},  class: 'button' %>
    <% if !session[:email].blank? %>
    < link_to "profile Img", profileimage_path(@profile),  class: 'button' %>
    <%=link_to "Manage Accounts",  users_path,class: 'button' if session[:privilege]  %>
    <%= link_to 'Logout',{:controller =>'sessions' ,:action => 'logout'},  class: 'button' %>
    <%end%>
    </div>
  </div>

  <% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert") %>
  <% end%>
  <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!-- here is the home page disagn that applay on all pages in app -->
<!DOCTYPE html>
<html>
  <head>
    <title>MaJeD BoJaN's article</title>

  	<%= csrf_meta_tags %>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=raleway:400,700'%>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_pack_tag 'test-react-bundle' %>

  </head>

<body>
  <div id="main_content">

    <div id="header">

      <img src="majed.jpg" class="img-circle img-responsive" alt="Cinque Terre" width="50px" right="6em" top="3em" >
        <%=link_to "Home",     root_path,  class: 'button' %>
        <%=link_to "Blogs",    root_path,  class: 'button' %>
        <%=link_to "Projects", root_path,  class: 'button' %>
        <%=link_to "About Us", pages_path,  class: 'button' %>
        <%=link_to "Contact",  new_contact_path,  class: 'button' %>
        <%=link_to "new post", new_post_path,  class: 'button' %>
    </div>

  <% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert") %>
  <% end%>
  <%= yield %>
  </div>
</body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>